// Game state types
export type GameState = "waiting" | "pre-launch" | "flying" | "landed" | "crashed";
export type TextureType =
  // Boat textures
  | "vintage"
  | "boat_1"
  | "boat_2"
  | "boat_3"
  // Platform textures
  | "metallic"
  | "metallic_1"
  | "metallic_2"
  | "metallic_3"
  | "gold"
  | "neon"
  | "night_sky"
  | "platform_1";
export type Environment = "space" | "sea" | "";

export interface LandingMetrics {
  position: {
    x: number;
    y: number;
    z: number;
  };
  velocity: {
    x: number;
    y: number;
    z: number;
  };
}
export interface RocketModel {
  id: string;
  name: string;
  url: string;
  position: { x: number; y: number; z: number };
  cameraPosition: { x: number; y: number; z: number };
  scale: { x: number; y: number; z: number };
  lights?: {
    type: string;
    color: string;
    intensity?: number;
    position?: { x: number; y: number; z: number };
  }[];
}
export interface GameStateValues {
  fuel: number;
  score: number;
  isLanded: boolean;
  gameState: GameState;
  textureChoice: TextureType;
  environment: Environment;
  currentLevel: number;
  isLevelCompleted: boolean;
}

// New interfaces for texture unlocking
export interface UnlockedTextures {
  sea: TextureType[];
  space: TextureType[];
}

export interface TextureUnlockTiers {
  sea: {
    tier1: TextureType[];
    tier2: TextureType[];
  };
  space: {
    tier1: TextureType[];
    tier2: TextureType[];
  };
}

export interface TextureUnlockNotification {
  show: boolean;
  environment: Environment;
  textures: TextureType[];
}

// New interfaces for rocket unlocking
export interface RocketUnlockNotification {
  show: boolean;
  rockets: string[];
}

export interface RocketAchievement {
  name: string;
  requirements: string[];
}

export interface RocketAchievements {
  [key: string]: RocketAchievement;
}

export interface UserAchievements {
  perfectLandings: number;
  highFuelLandings: number;
  lowVelocityLandings: number;
  highScores: number[];
  totalLandings: number;
  completedAllLevels: boolean;
  lowVelocityInSpaceLevel3: boolean;
  highFuelInSpaceLevel3: boolean;
}

// Leaderboard interfaces
export interface LeaderboardEntry {
  id?: string; // Document ID (auto-generated by Firestore)
  uuid: string; // User's UUID
  username: string; // User's display name
  spaceScore: number; // Cumulative score for space environment
  seaScore: number; // Cumulative score for sea environment
  totalScore: number; // Total cumulative score (space + sea)
  lastUpdated: Date; // When the score was last updated
  rocketId: string; // Last used rocket model
  fuelRemaining: number; // Last landing fuel percentage
  landingVelocity: number; // Last landing velocity
}

export interface LeaderboardStats {
  personalBest: number; // User's highest score
  totalEntries: number; // Total number of entries in the leaderboard
  recentEntries: LeaderboardEntry[]; // Recent entries
}
